site_name: Normativa GLRP
theme:
  name: material
  palette:
    scheme: slate
    primary: yellow
    accent: red
nav:
  - Normativa General: index.md
  - Normas Ilegales: ilegales.md
  - Facciones Principales: facciones.md
