site_name: Normativa SA-MP
theme:
  name: material
  palette:
    scheme: slate
    primary: yellow
    accent: red
nav:
  - Normativa General: normativa.md
  - Normas Ilegales: ilegales.md
  - Facciones Principales: facciones.md
